apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: amoctagon/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: amoctagon/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: proamar/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
