apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: proamar/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
